### ISSUE TITLE
'stdin: is not a tty' in the footer

### ISSUE THREAD

**Issue by kazgurs** [hashicorp/www#168]
Looks quite cool, but I doubt you intended to leave it there:)
![screen shot 2016-01-27 at 10 39 49 am](https://cloud.githubusercontent.com/assets/12516828/12608608/b51001de-c4e5-11e5-839e-14c3d9e4a095.png)

**Comment by sethvargo** [comment]
This is intended. https://github.com/hashicorp/www/pull/87

**Comment by kazgurs** [comment]
Oops, sorry :)
