### ISSUE TITLE
Jobs page can't load js from from www subdomain

### ISSUE THREAD

**Issue by catsby** [hashicorp/www#30]
There's a route error (or something) with the javascript file(s) required on hashicorp.com/jobs.html.

```console
$  curl https://www.hashicorp.com/javascripts/hashicorp-3be9fdc1.js      
File not found: /javascripts/hashicorp-3be9fdc1.js
 
$  curl https://hashicorp.com/javascripts/hashicorp-3be9fdc1.js
!function(t,e)[...]
```

As a result, clicking on any of the jobs on https://www.hashicorp.com/jobs.html does nothing for me, but https://hashicorp.com/jobs.html# works as expected.

**Comment by ryanuber** [comment]
I tried this from my machine and don't see the problem. It seems like maybe a CDN thing.

**Comment by ryanuber** [comment]
This should be fixed!
