### ISSUE TITLE
Deleting a build configuration and re-pushing via packer does not work

### ISSUE THREAD

**Issue by gitttt** [hashicorp/www#38]
Step1: From the from the web interface: Go to Builds, Click on an existing build configuration, click on Settings, click "Delete build configuration"

Step2: From the console: "packer push -create template.json", Inside the template.json: "push": {
"name": "some_name/same_name_as_the_one_from_the_delete_build_configuration"
A message says "Push successful" but there is no new build configuration visible in the web interface.

**Comment by sethvargo** [comment]
Hi there,

This is an item on our roadmap to fix shortly. If you would like us to restore a specific build configuration, please email support@hashicorp.com with the build configuration id. Thank you!
